# Generated by Django 3.2 on 2021-04-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrels',
            fields=[
                ('X', models.FloatField(help_text='Longitude')),
                ('Y', models.FloatField(help_text='Latitude')),
                ('Unique_Squirrel_ID', models.CharField(default=None, help_text='Unique Squirrel ID', max_length=50, primary_key=True, serialize=False)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=2)),
                ('Date', models.DateField(blank=True, help_text='Date')),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], max_length=50, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=50, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=50, null=True)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific_Location', max_length=255, null=True)),
                ('Running', models.BooleanField(default=False, help_text='Is the squirrel running?')),
                ('Chasing', models.BooleanField(default=False, help_text='Is the squirrel chasing?')),
                ('Climbing', models.BooleanField(default=False, help_text='Is the squirrel climbing?')),
                ('Eating', models.BooleanField(default=False, help_text='Is the squirrel eating?')),
                ('Foraging', models.BooleanField(default=False, help_text='Is the squirrel foraging?')),
                ('Other_Activities', models.TextField(blank=True, help_text='Other activites', max_length=100, null=True)),
                ('Kuks', models.BooleanField(default=False, help_text='Is the squirrel kuking?')),
                ('Quaas', models.BooleanField(default=False, help_text='Is the squirrel quaaing?')),
                ('Moans', models.BooleanField(default=False, help_text='Is the squirrel moaning?')),
                ('Tail_Flags', models.BooleanField(default=False, help_text='Does the squirrel have a tail flag?')),
                ('Tail_Twitches', models.BooleanField(default=False, help_text="Is the squirrel's tail twitching?")),
                ('Approaches', models.BooleanField(default=False, help_text='Did the squirrel approach you?')),
                ('Indifferent', models.BooleanField(default=False, help_text='Was the squirrel indifferent to you?')),
                ('Runs_From', models.BooleanField(default=False, help_text='Did the squirrel run from you?')),
            ],
        ),
    ]
